#!/bin/bash
set -euo pipefail
# -e : immediately exit if any command has a non-zero exit status.
# -u : program to immediately exit on references for any variable you haven't previously defined
# -o pipefail : any command in a pipeline that fails the return code will be used as the return code of the whole pipeline

############# Helper functions #############

# More ideas: https://raw.githubusercontent.com/sindresorhus/cli-spinners/master/spinners.json
SPIN_FORM=(▰▱▱▱▱▱▱ ▰▰▱▱▱▱▱ ▰▰▰▱▱▱▱ ▰▰▰▰▱▱▱ ▰▰▰▰▰▱▱ ▰▰▰▰▰▰▱ ▰▰▰▰▰▰▰)
# Restarting fzf immediately may not show the newly created changes. Wait at least a second or two.
_load_indicator() {
	printf "\n\n%s\n" "$1"
	for i in "${SPIN_FORM[@]}"; do
		echo -ne "\r$i"
		sleep "$2"
	done
}

# Redefine this function to change the options
# https://github.com/junegunn/fzf-git.sh/blob/main/fzf-git.sh#L104
_fzf_basic_options() {
	fzf -- \
		--ansi --layout reverse --info inline --no-multi --height 100% \
		--header '' --ellipsis '' --border horizontal \
		--preview-window "$PREVIEW_WINDOW_VISIBILITY:wrap:right:50%:border-left" "$@"
}

############# Manual #############
HELP_GENERAL='cat <<<"
gh look [Command] [-Flags] [Search term]

Command │ Description
────────│───────────────
issue   │ List issues
pr      │ List pull requests"'

HELP_ISSUE_SECTION='cat <<<"
gh look issue [-Flags] [Search term]

Flags  │ Description
───────│───────────────
<none> │ List issues from current directory
-e     │ Emoji to make a reaction (default: THUMBS_UP 👍 )
       │  {CONFUSED,EYES,HEART,HOORAY,LAUGH,THUMBS_DOWN,THUMBS_UP,ROCKET}
-o     │ sorting order of issues (default: created-desc)
       │  {author-date,committer-date,created,interactions,reactions,updated}-{desc,asc}
-R     │ Specify a repository (form: OWNER/REPO)
-w     │ Display the preview window upon start (default: hidden)

Head  │ Description
──────│───────────────
💬    │ Total number of comments (gray commentable; red locked)
📣    │ Total number of emojis (green reactable; yellow reacted; red locked)

HotKeys  │ Description
─────────│───────────────
<search> │ https://docs.github.com/en/search-github/searching-on-github
         │  (Example: sort:reactions is:closed author:@me Autobahn)
?        │ Toggle help
enter    │ See comments
tab      │ Toggle issue preview
ctrl+a   │ ALL issues
ctrl+b   │ Browser
ctrl+e   │ Edit an issue
ctrl+f   │ Fuzzy search
ctrl+n   │ New issue
ctrl+o   │ OPEN issues only
ctrl+t   │ React with an Emoji
ctrl+u   │ Undo the Emoji reaction
ctrl+x   │ Write a comment
esc      │ Exit"'

###################################### ISSUE

_fzf_issue() {
	# fzf allows hiding columns "--with-nth 2...", headers are also affected, so NODE_ID_HIDDEN is included there
	# when columns are hidden the number on GH_FORCE_TTY needs to be increased
	GH_ISSUE_COMMAND=$'gh api graphql --raw-field query=\'query($filter: String!) {search(query: $filter, type: ISSUE, first: 75) {issueCount nodes { ... on Issue { author { login } comments {totalCount} id number updatedAt reactions { totalCount viewerHasReacted } state title viewerCanReact viewerDidAuthor }}}}\' --template \'
		{{- $limitCount := .data.search.issueCount -}}
			{{- if gt .data.search.issueCount 75.0 -}}{{- $limitCount = 75.0 -}}{{- end -}}
		{{- tablerow "NODE_ID_HIDDEN" (printf "%.0f of ∑ %.0f Issues" $limitCount .data.search.issueCount | color "blue+b") ("|" | color "white+d") ("? - Toggle Help" | color "blue+d") -}}{{- tablerender -}}
		{{- tablerow "" -}}{{- tablerender -}}
		{{- $headerColor := "blue+bd" -}}
			{{- tablerow "NODE_ID_HIDDEN" ("ISSUE" | color $headerColor) ("AUTHOR" | color $headerColor) ("LAST UPDATE" | color $headerColor) "💬" "📣" ("TITLE" | color $headerColor) -}}
		{{- range .data.search.nodes -}}
			{{- $stateIssueColor := "green" -}}
				{{- if eq .state "CLOSED" -}}{{- $stateIssueColor = "93" -}}{{- end -}}
			{{- $author := "[DELETED_USER]" -}}
				{{- if .author -}}{{- $author = .author.login -}}{{- end -}}
			{{- $authorColor := "cyan+h" -}}
				{{- if .viewerDidAuthor -}}{{- $authorColor = "yellow+b" -}}{{- end -}}
			{{- $commentCount := "\u00a0" -}}{{- /* Remark: U+00a0 (non-breaking space) for entries without comments, which the viewer can comment on. Needed to make a if decision with fzf later in the script. */ -}}
				{{- if not .viewerCanReact -}}{{- $commentCount = (or (printf "%.0f" .comments.totalCount) "0")  -}}
					{{- else if .comments.totalCount -}}{{- $commentCount = printf "%.0f" .comments.totalCount -}}
				{{- end -}}
			{{- $commentColor := "white+bd" -}}
				{{- if not .viewerCanReact -}}{{- $commentColor = "red+bd" -}}{{- end -}}
			{{- $emojiCount := "" -}}
				{{- if not .viewerCanReact -}}{{- $emojiCount = (or (printf "%.0f" .reactions.totalCount) "0")  -}}
					{{- else if .reactions.totalCount -}}{{- $emojiCount = printf "%.0f" .reactions.totalCount -}}
				{{- end -}}
			{{- $emojiColor := "green+bd" -}}
				{{- if not .viewerCanReact -}}{{- $emojiColor = "red+bd" -}}
					{{- else if .reactions.viewerHasReacted -}}{{- $emojiColor = "yellow+b" -}}
				{{- end -}}
			{{- tablerow .id (printf "#%.0f" .number | color $stateIssueColor) ($author | color $authorColor) (timeago .updatedAt) ($commentCount | color $commentColor) ($emojiCount | color $emojiColor) .title -}}
		{{- end -}}\''

	INITIAL_ISSUE_PROMPT=$(grep -q A <"$SCRATCH_FILE" && printf "ALL ◉ [%s] > " "$OWNER_REPO_NAME" || printf "\e[1;92mOPEN ◉ [%s] > " "$OWNER_REPO_NAME")

	ISSUE_OUTPUT=$(FZF_DEFAULT_COMMAND="(grep -q A <$SCRATCH_FILE && $GH_ISSUE_COMMAND --raw-field filter=\"$SORTING_ORDER type:issue repo:$OWNER_REPO_NAME $INITIAL_QUERY \" || $GH_ISSUE_COMMAND --raw-field filter=\"$SORTING_ORDER type:issue repo:$OWNER_REPO_NAME state:open $INITIAL_QUERY \") || true" \
		GH_FORCE_TTY=125% _fzf_basic_options --disabled --header-lines 3 --with-nth 2.. \
		--prompt "$INITIAL_ISSUE_PROMPT" \
		--query "$INITIAL_QUERY" --preview "gh issue view {2} --repo $OWNER_REPO_NAME --comments" \
		--bind "change:first+reload:sleep 0.25; (grep -q A <$SCRATCH_FILE && $GH_ISSUE_COMMAND --raw-field filter=\"$SORTING_ORDER type:issue repo:$OWNER_REPO_NAME \"{q} || $GH_ISSUE_COMMAND --raw-field filter=\"$SORTING_ORDER type:issue repo:$OWNER_REPO_NAME state:open \"{q}) || true" \
		--bind "?:toggle-preview+change-preview:$HELP_ISSUE_SECTION" \
		--bind "tab:toggle-preview+change-preview:gh issue view {2} --repo $OWNER_REPO_NAME --comments" \
		--bind "ctrl-a:rebind(change)+change-prompt(ALL ◉ [$OWNER_REPO_NAME] > )+disable-search+execute-silent(echo A >$SCRATCH_FILE)+reload:$GH_ISSUE_COMMAND --raw-field filter=\"$SORTING_ORDER type:issue repo:$OWNER_REPO_NAME \"{q} || true" \
		--bind "ctrl-b:execute-silent(gh issue view {2} --web --repo $OWNER_REPO_NAME)" \
		--bind $'ctrl-f:unbind(change)+enable-search+clear-query+change-prompt(\e[1;93mFUZZY SEARCH'" [$OWNER_REPO_NAME] > )" \
		--bind $'ctrl-o:rebind(change)+change-prompt(\e[1;92mOPEN ◉'" [$OWNER_REPO_NAME] > )+disable-search+execute-silent(echo B >$SCRATCH_FILE)+reload:$GH_ISSUE_COMMAND --raw-field filter=\"$SORTING_ORDER type:issue repo:$OWNER_REPO_NAME state:open \"{q} || true" \
		--bind "ctrl-t:execute-silent($GH_ADD_REACTION --raw-field id={1} --raw-field emoji=$REACTION_EMOJI)+reload:(grep -q A <$SCRATCH_FILE && $GH_ISSUE_COMMAND --raw-field filter=\"$SORTING_ORDER type:issue repo:$OWNER_REPO_NAME \"{q} || $GH_ISSUE_COMMAND --raw-field filter=\"$SORTING_ORDER type:issue repo:$OWNER_REPO_NAME state:open \"{q}) || true" \
		--bind "ctrl-u:execute-silent($GH_REMOVE_REACTION --raw-field id={1} --raw-field emoji=$REACTION_EMOJI)+reload:(grep -q A <$SCRATCH_FILE && $GH_ISSUE_COMMAND --raw-field filter=\"$SORTING_ORDER type:issue repo:$OWNER_REPO_NAME \"{q} || $GH_ISSUE_COMMAND --raw-field filter=\"$SORTING_ORDER type:issue repo:$OWNER_REPO_NAME state:open \"{q}) || true" \
		--expect "ctrl-e,ctrl-n,ctrl-x,enter")

	ISSUE_NUMBER=$(sed 1d <<<"${ISSUE_OUTPUT}" | awk '{print $2}' | tr -d "#")
	case $(sed 1q <<<"${ISSUE_OUTPUT}") in
	ctrl-e)
		gh issue edit "$ISSUE_NUMBER" --repo "$OWNER_REPO_NAME"
		_load_indicator "Restarting ..." 0.25
		_fzf_issue
		;;
	ctrl-n)
		gh issue create --repo "$OWNER_REPO_NAME"
		_load_indicator "Restarting ..." 0.25
		_fzf_issue
		;;
	ctrl-x)
		gh issue comment "$ISSUE_NUMBER" --repo "$OWNER_REPO_NAME"
		_load_indicator "Restarting ..." 0.25
		_fzf_issue
		;;
	enter) _fzf_issue_comment ;;
	esac
}
_fzf_issue_comment() {
	if ! sed 1d <<<"${ISSUE_OUTPUT}" | awk '{print $6,$7}' | grep -Eqw '[0-9]+'; then
		# adding U+00a0 (non-breaking space) for isues with zero comments and commentable
		# without it an issue with 0 comments and >1 reaction would trick the if check
		# sometimes the "age" column can only be 2 words instead of 3, e.g. "just now", that is why $6 and $7
		_load_indicator $'No comments on this issue\nRestarting ...' 0.45
		_fzf_issue
	fi
	HELP_ISSUE_COMMENT_SECTION='cat <<<"
Head │ Description
─────│───────────────
📣   │ Total number of emojis (green reactable; yellow reacted; red locked)

HotKeys  │ Description
─────────│───────────────
?        │ Toggle help
tab      │ Toggle comment preview
ctrl+b   │ Browser
ctrl+n   │ New issue
ctrl+t   │ React with an Emoji
ctrl+u   │ Undo the Emoji reaction
ctrl+x   │ Write a comment
ctrl+z   │ Delete the comment after confirmation
esc      │ Return to to issue list"'

	GH_ISSUE_COMMENTS_COMMAND=$'gh api graphql --paginate --raw-field query=\'query ($owner: String!, $name: String!, $number: Int!, $endCursor: String) { repository(owner: $owner, name: $name) { issue(number: $number) { author { login } createdAt number state title comments(first: 100, after: $endCursor) { totalCount nodes { author { login } body createdAt databaseId id reactions { totalCount viewerHasReacted } viewerCanReact viewerDidAuthor } pageInfo { endCursor hasNextPage }}}}}\' --template \'
		{{- $prefix := .data.repository.issue -}}
		{{- $stateIssueCommentColor := "green" -}}
			{{- if eq $prefix.state "CLOSED" -}}{{- $stateIssueCommentColor = "93" -}}{{- end -}}
			{{- tablerow "NODE_ID_HIDDEN" "DATABASE_ID_HIDDEN" ($prefix.title | color "white+bh") -}}{{- tablerender -}}
		{{- $issueAuthor := "[DELETED_USER]" -}}
			{{- if $prefix.author -}}{{- $issueAuthor = $prefix.author.login -}}{{- end -}}
			{{- tablerow "NODE_ID_HIDDEN" "DATABASE_ID_HIDDEN" (printf "%s ◉ #%.0f" $prefix.state $prefix.number | color $stateIssueCommentColor) ($issueAuthor | color "cyan+hb") (printf "│ %s ∙ %.0f Comments │" (timeago $prefix.createdAt) $prefix.comments.totalCount | color "gray+h") ("? - Toggle Help" | color "blue+d") -}}{{- tablerender -}}
			{{- tablerow "NODE_ID_HIDDEN" "DATABASE_ID_HIDDEN" (printf "———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————"| color "gray+d") -}}{{- tablerender -}}
			{{- tablerow "NODE_ID_HIDDEN" "DATABASE_ID_HIDDEN" "" -}}{{- tablerender -}}
		{{- $headerColor := "blue+bd" -}}
			{{- tablerow "NODE_ID_HIDDEN" "DATABASE_ID_HIDDEN" ("COMMENTER" | color $headerColor) ("AGE" | color $headerColor) "📣" ("TITLE" | color $headerColor) -}}
		{{- range $prefix.comments.nodes -}}
			{{- $author := "[DELETED_USER]" -}}
				{{- if .author -}}{{- $author = .author.login -}}{{- end -}}
			{{- $authorColor := "cyan+h" -}}
				{{- if .viewerDidAuthor -}}{{- $authorColor = "yellow+b" -}}{{- end -}}
			{{- $emojiCount := "" -}}
				{{- if not .viewerCanReact -}}{{- $emojiCount = (or (printf "%.0f" .reactions.totalCount) "0")  -}}
					{{- else if .reactions.totalCount -}}{{- $emojiCount = printf "%.0f" .reactions.totalCount -}}
				{{- end -}}
			{{- $emojiColor := "green+bd" -}}
				{{- if not .viewerCanReact -}}{{- $emojiColor = "red+bd" -}}
					{{- else if .reactions.viewerHasReacted -}}{{- $emojiColor = "yellow+b" -}}
				{{- end -}}
			{{- tablerow .id .databaseId ($author | color $authorColor) (timeago .createdAt) ($emojiCount | color $emojiColor) .body -}}
		{{- end -}}\''

	ISSUE_COMMENT_OUTPUT=$(FZF_DEFAULT_COMMAND="$GH_ISSUE_COMMENTS_COMMAND --raw-field owner=${OWNER_REPO_NAME%/*} --raw-field name=${OWNER_REPO_NAME#*/} --field number=$ISSUE_NUMBER" \
		GH_FORCE_TTY=150% _fzf_basic_options --header-lines 5 --with-nth 3.. \
		--prompt $'\e[1;94m'"Issue 💬 [$OWNER_REPO_NAME] > " \
		--preview-window "+4:~4" --preview "$GH_COMMENTS_PREVIEW" \
		--bind "?:toggle-preview+change-preview:$HELP_ISSUE_COMMENT_SECTION" \
		--bind "tab:toggle-preview+change-preview:$GH_COMMENTS_PREVIEW" \
		--bind "ctrl-b:execute-silent(open https://github.com/$OWNER_REPO_NAME/issues/$ISSUE_NUMBER#issuecomment-{2})" \
		--bind "ctrl-t:execute-silent($GH_ADD_REACTION --raw-field id={1} --raw-field emoji=$REACTION_EMOJI)+reload:$GH_ISSUE_COMMENTS_COMMAND --raw-field owner=${OWNER_REPO_NAME%/*} --raw-field name=${OWNER_REPO_NAME#*/} --field number=$ISSUE_NUMBER || true" \
		--bind "ctrl-u:execute-silent($GH_REMOVE_REACTION --raw-field id={1} --raw-field emoji=$REACTION_EMOJI)+reload:$GH_ISSUE_COMMENTS_COMMAND --raw-field owner=${OWNER_REPO_NAME%/*} --raw-field name=${OWNER_REPO_NAME#*/} --field number=$ISSUE_NUMBER || true" \
		--expect "ctrl-n,ctrl-x,ctrl-z,esc")

	case $(sed 1q <<<"${ISSUE_COMMENT_OUTPUT}") in
	ctrl-n)
		gh issue create --repo "$OWNER_REPO_NAME"
		_load_indicator "Restarting ..." 0.25
		_fzf_issue
		;;
	ctrl-x)
		gh issue comment "$ISSUE_NUMBER" --repo "$OWNER_REPO_NAME"
		_load_indicator "Restarting ..." 0.25
		_fzf_issue_comment
		;;
	ctrl-z)
		printf "\n%s\n\nCONFIRM DELETION (Y/n) " "$(sed 1d <<<"${ISSUE_COMMENT_OUTPUT}" | awk '{$1=$2=""; print $0}')"
		stty raw -echo
		CONFIRM=$(dd bs=1 count=1 2>/dev/null)
		stty sane
		if [[ "$CONFIRM" = "y" ]]; then
			gh api graphql --silent --raw-field id="$(sed 1d <<<"${ISSUE_COMMENT_OUTPUT}" | awk '{print $1}')" --raw-field query=$'mutation($id: ID!) { deleteIssueComment(input: {id: $id}) { clientMutationId }}' 2>/dev/null && printf "\n🟢 Success.... comment deleted\n" || printf "\n🛑 Missing permissions to delete this comment. !!!\n"
			_load_indicator "Restarting ..." 0.25
			_fzf_issue
		else
			printf "\nDiscarding... comment was not delted !!!"
			_load_indicator "Restarting ..." 0.25
			_fzf_issue_comment
		fi
		;;
	esc) _fzf_issue ;;
	esac
}

###################################### PULL-REQUEST (PR)

HELP_PR_SECTION='cat <<<"
gh look pr [-Flags] [Search term]

Flags  │ Description
───────│───────────────
<none> │ List pull requests from current directory
-e     │ Emoji to make a reaction (default: THUMBS_UP 👍 )
       │  {CONFUSED,EYES,HEART,HOORAY,LAUGH,THUMBS_DOWN,THUMBS_UP,ROCKET}
-o     │ sorting order of pull requests (default: created-desc)
       │  {author-date,committer-date,created,interactions,reactions,updated}-{desc,asc}
-R     │ Specify a repo (form: OWNER/REPO)
-w     │ Display the preview window upon start (default: hidden)

Head  │ Description
──────│───────────────
💬    │ Total number of comments (gray commentable; red locked)
📣    │ Total number of emojis (green reactable; yellow reacted; red locked)
+     │ Additions
-     │ Deletions

HotKeys  │ Description
─────────│───────────────
<search> │ https://docs.github.com/en/search-github/searching-on-github
         │  (Example: sort:reactions is:closed author:@me Autobahn)
?        │ Toggle help
enter    │ See comments
tab      │ Toggle pull request preview
ctrl+a   │ ALL pull requests
ctrl+b   │ Browser
ctrl+d   │ Toggle diff
ctrl+e   │ Edit a pull request
ctrl+f   │ Fuzzy search
ctrl+g   │ Merge a pull request
ctrl+o   │ OPEN pull requests only
ctrl+t   │ React with an Emoji
ctrl+u   │ Undo the Emoji reaction
ctrl+x   │ Write a comment
ctrl+y   │ Checkout
esc      │ Exit"'

_fzf_pr() {
	# fzf allows hiding columns "--with-nth 2...", headers are also affected, so NODE_ID_HIDDEN is included there
	# when columns are hidden the number on GH_FORCE_TTY needs to be increased
	GH_PR_COMMAND=$'gh api graphql --raw-field query=\'query($filter: String!) {search(query: $filter, type: ISSUE, first: 75) {issueCount nodes { ... on PullRequest { additions author { login } comments {totalCount} deletions id number updatedAt reactions { totalCount viewerHasReacted } state title viewerCanReact viewerDidAuthor }}}}\' --template \'
		{{- $limitCount := .data.search.issueCount -}}
			{{- if gt .data.search.issueCount 75.0 -}}{{- $limitCount = 75.0 -}}{{- end -}}
		{{- tablerow "NODE_ID_HIDDEN" (printf "%.0f of ∑ %.0f Pull requests" $limitCount .data.search.issueCount | color "blue+b") ("|" | color "white+d") ("? - Toggle Help" | color "blue+d") -}}{{- tablerender -}}
		{{- tablerow "" -}}{{- tablerender -}}
		{{- $headerColor := "blue+bd" -}}
			{{- tablerow "NODE_ID_HIDDEN" ("PR" | color $headerColor) ("AUTHOR" | color $headerColor) ("LAST UPDATE" | color $headerColor) "💬" "📣" ("+" | color "green+bd") ("-" | color "red+bd") ("TITLE" | color $headerColor) -}}
		{{- range .data.search.nodes -}}
			{{- $statePullRequestColor := "green" -}}
				{{- if eq .state "CLOSED" }}{{ $statePullRequestColor = "red" }}{{- else if eq .state "MERGED" }}{{ $statePullRequestColor = "magenta" }}{{ end -}}
			{{- $author := "[DELETED_USER]" -}}
				{{- if .author -}}{{- $author = .author.login -}}{{- end -}}
			{{- $authorColor := "cyan+h" -}}
				{{- if .viewerDidAuthor -}}{{- $authorColor = "yellow+b" -}}{{- end -}}
			{{- $commentCount := "\u00a0" -}}{{- /* Remark: U+00a0 (non-breaking space) for entries without comments, which the viewer can comment on. Needed to make a if decision with fzf later in the script. */ -}}
				{{- if not .viewerCanReact -}}{{- $commentCount = (or (printf "%.0f" .comments.totalCount) "0")  -}}
					{{- else if .comments.totalCount -}}{{- $commentCount = printf "%.0f" .comments.totalCount -}}
				{{- end -}}
			{{- $commentColor := "white+bd" -}}
				{{- if not .viewerCanReact -}}{{- $commentColor = "red+bd" -}}{{- end -}}
			{{- $emojiCount := "" -}}
				{{- if not .viewerCanReact -}}{{- $emojiCount = (or (printf "%.0f" .reactions.totalCount) "0")  -}}
					{{- else if .reactions.totalCount -}}{{- $emojiCount = printf "%.0f" .reactions.totalCount -}}
				{{- end -}}
			{{- $emojiColor := "green+bd" -}}
				{{- if not .viewerCanReact -}}{{- $emojiColor = "red+bd" -}}
					{{- else if .reactions.viewerHasReacted -}}{{- $emojiColor = "yellow+b" -}}
				{{- end -}}
			{{- tablerow .id (printf "#%.0f" .number | color $statePullRequestColor) ($author | color $authorColor) (timeago .updatedAt) ($commentCount | color $commentColor) ($emojiCount | color $emojiColor) (printf "+%.0f" .additions | color "green") (printf "-%.0f" .deletions | color "red") .title -}}
		{{- end -}}\''

	INITIAL_PR_PROMPT=$(grep -q A <"$SCRATCH_FILE" && printf "ALL ╫ [%s] > " "$OWNER_REPO_NAME" || printf "\e[1;92mOPEN ╫ [%s] > " "$OWNER_REPO_NAME")

	PR_OUTPUT=$(FZF_DEFAULT_COMMAND="(grep -q A <$SCRATCH_FILE && $GH_PR_COMMAND --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME $INITIAL_QUERY \" || $GH_PR_COMMAND --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME state:open $INITIAL_QUERY \") || true" \
		GH_FORCE_TTY=125% _fzf_basic_options --disabled --header-lines 3 --with-nth 2.. \
		--prompt "$INITIAL_PR_PROMPT" \
		--query "$INITIAL_QUERY" --preview "gh pr view {2} --repo $OWNER_REPO_NAME --comments" \
		--bind "change:first+reload:sleep 0.25; (grep -q A <$SCRATCH_FILE && $GH_PR_COMMAND --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME \"{q} || $GH_PR_COMMAND --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME state:open \"{q}) || true" \
		--bind "?:toggle-preview+change-preview:$HELP_PR_SECTION" \
		--bind "tab:toggle-preview+change-preview:gh pr view {2} --repo $OWNER_REPO_NAME --comments" \
		--bind "ctrl-a:rebind(change)+change-prompt(ALL ╫ [$OWNER_REPO_NAME] > )+disable-search+execute-silent(echo A >$SCRATCH_FILE)+reload:$GH_PR_COMMAND --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME \"{q} || true" \
		--bind "ctrl-b:execute-silent(gh pr view {2} --web --repo $OWNER_REPO_NAME)" \
		--bind $'ctrl-f:unbind(change)+enable-search+clear-query+change-prompt(\e[1;93mFUZZY SEARCH'" [$OWNER_REPO_NAME] > )" \
		--bind "ctrl-d:toggle-preview+change-preview(gh pr diff {2} --repo $OWNER_REPO_NAME"$' | if type delta &>/dev/null; then delta --width ${FZF_PREVIEW_COLUMNS:-$COLUMNS}; else cat; fi)' \
		--bind $'ctrl-o:rebind(change)+change-prompt(\e[1;92mOPEN ╫'" [$OWNER_REPO_NAME] > )+disable-search+execute-silent(echo B >$SCRATCH_FILE)+reload:$GH_PR_COMMAND --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME state:open \"{q} || true" \
		--bind "ctrl-t:execute-silent($GH_ADD_REACTION --raw-field id={1} --raw-field emoji=$REACTION_EMOJI)+reload:(grep -q A <$SCRATCH_FILE && $GH_PR_COMMAND --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME \"{q} || $GH_PR_COMMAND --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME state:open \"{q}) || true" \
		--bind "ctrl-u:execute-silent($GH_REMOVE_REACTION --raw-field id={1} --raw-field emoji=$REACTION_EMOJI)+reload:(grep -q A <$SCRATCH_FILE && $GH_PR_COMMAND --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME \"{q} || $GH_PR_COMMAND --raw-field filter=\"$SORTING_ORDER type:pr repo:$OWNER_REPO_NAME state:open \"{q}) || true" \
		--expect "ctrl-e,ctrl-g,ctrl-x,ctrl-y,enter")

	PR_NUMBER=$(sed 1d <<<"${PR_OUTPUT}" | awk '{print $2}' | tr -d "#")
	case $(sed 1q <<<"${PR_OUTPUT}") in
	ctrl-e)
		gh pr edit "$PR_NUMBER" --repo "$OWNER_REPO_NAME"
		_load_indicator "Restarting ..." 0.25
		_fzf_pr
		;;
	ctrl-g)
		gh pr merge "$PR_NUMBER" --repo "$OWNER_REPO_NAME"
		exit 0
		;;
	ctrl-x)
		gh pr comment "$PR_NUMBER" --repo "$OWNER_REPO_NAME"
		_load_indicator "Restarting ..." 0.25
		_fzf_pr
		;;
	ctrl-y)
		gh pr checkout "$PR_NUMBER" --repo "$OWNER_REPO_NAME"
		exit 0
		;;
	enter) _fzf_pr_comment ;;
	esac
}
_fzf_pr_comment() {
	if ! sed 1d <<<"${PR_OUTPUT}" | awk '{print $6,$7}' | grep -Eqw '[0-9]+'; then
		_load_indicator $'No comments on this pull request\nRestarting ...' 0.45
		_fzf_pr
	fi
	HELP_PR_COMMENT_SECTION='cat <<<"
Head │ Description
─────│───────────────
📣   │ Total number of emojis (green reactable; yellow reacted; red locked)

HotKeys  │ Description
─────────│───────────────
?        │ Toggle help
tab      │ Toggle comment preview
ctrl+b   │ Browser
ctrl+d   │ Toggle diff
ctrl+t   │ React with an Emoji
ctrl+u   │ Undo the Emoji reaction
ctrl+x   │ Write a comment
esc      │ Return to pull request list"'

	GH_PR_COMMENTS_COMMAND=$'gh api graphql --paginate --raw-field query=\'query ($owner: String!, $name: String!, $number: Int!, $endCursor: String) { repository(owner: $owner, name: $name) { pullRequest(number: $number) { author { login } createdAt number state title comments(first: 100, after: $endCursor) { totalCount nodes { author { login } body createdAt databaseId id reactions { totalCount viewerHasReacted } viewerCanReact viewerDidAuthor } pageInfo { endCursor hasNextPage }}}}}\' --template \'
		{{- $prefix := .data.repository.pullRequest -}}
		{{- $statePullRequestCommentColor := "green" -}}
			{{- if eq $prefix.state "CLOSED" -}}{{- $statePullRequestCommentColor = "red" -}}{{- else if eq $prefix.state "MERGED" }}{{- $statePullRequestCommentColor = "magenta" -}}{{- end -}}
			{{- tablerow "NODE_ID_HIDDEN" "DATABASE_ID_HIDDEN" ($prefix.title | color "white+bh") -}}{{- tablerender -}}
		{{- $pullRequestAuthor := "[DELETED_USER]" -}}
			{{- if $prefix.author -}}{{- $pullRequestAuthor = $prefix.author.login -}}{{- end -}}
			{{- tablerow "NODE_ID_HIDDEN" "DATABASE_ID_HIDDEN" (printf "%s ╫ #%.0f" $prefix.state $prefix.number | color $statePullRequestCommentColor) ($pullRequestAuthor | color "cyan+hb") (printf "│ %s ∙ %.0f Comments │" (timeago $prefix.createdAt) $prefix.comments.totalCount | color "gray+h") ("? - Toggle Help" | color "blue+d") -}}{{- tablerender -}}
			{{- tablerow "NODE_ID_HIDDEN" "DATABASE_ID_HIDDEN" (printf "———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————"| color "gray+d") -}}{{- tablerender -}}
			{{- tablerow "NODE_ID_HIDDEN" "DATABASE_ID_HIDDEN" "" -}}{{- tablerender -}}
		{{- $headerColor := "blue+bd" -}}
			{{- tablerow "NODE_ID_HIDDEN" "DATABASE_ID_HIDDEN" ("COMMENTER" | color $headerColor) ("AGE" | color $headerColor) "📣" ("TITLE" | color $headerColor) -}}
		{{- range $prefix.comments.nodes -}}
			{{- $author := "[DELETED_USER]" -}}
				{{- if .author -}}{{- $author = .author.login -}}{{- end -}}
			{{- $authorColor := "cyan+h" -}}
				{{- if .viewerDidAuthor -}}{{- $authorColor = "yellow+b" -}}{{- end -}}
			{{- $emojiCount := "" -}}
				{{- if not .viewerCanReact -}}{{- $emojiCount = (or (printf "%.0f" .reactions.totalCount) "0")  -}}
					{{- else if .reactions.totalCount -}}{{- $emojiCount = printf "%.0f" .reactions.totalCount -}}
				{{- end -}}
			{{- $emojiColor := "green+bd" -}}
				{{- if not .viewerCanReact -}}{{- $emojiColor = "red+bd" -}}
					{{- else if .reactions.viewerHasReacted -}}{{- $emojiColor = "yellow+b" -}}
				{{- end -}}
			{{- tablerow .id .databaseId ($author | color $authorColor) (timeago .createdAt) ($emojiCount | color $emojiColor) .body -}}
		{{- end -}}\''

	PR_COMMENT_OUTPUT=$(FZF_DEFAULT_COMMAND="$GH_PR_COMMENTS_COMMAND --raw-field owner=${OWNER_REPO_NAME%/*} --raw-field name=${OWNER_REPO_NAME#*/} --field number=$PR_NUMBER" \
		GH_FORCE_TTY=150% _fzf_basic_options --header-lines 5 --with-nth 3.. \
		--prompt $'\e[1;94m'"Pull request 💬 [$OWNER_REPO_NAME] > " \
		--preview-window "+4:~4" --preview "$GH_COMMENTS_PREVIEW" \
		--bind "?:toggle-preview+change-preview:$HELP_PR_COMMENT_SECTION" \
		--bind "tab:toggle-preview+change-preview:$GH_COMMENTS_PREVIEW" \
		--bind "ctrl-b:execute-silent(open https://github.com/$OWNER_REPO_NAME/pull/$PR_NUMBER#issuecomment-{2})" \
		--bind "ctrl-d:toggle-preview+change-preview(gh pr diff $PR_NUMBER --repo $OWNER_REPO_NAME"$' | if type delta &>/dev/null; then delta --width ${FZF_PREVIEW_COLUMNS:-$COLUMNS}; else cat; fi)' \
		--bind "ctrl-t:execute-silent($GH_ADD_REACTION --raw-field id={1} --raw-field emoji=$REACTION_EMOJI)+reload:$GH_PR_COMMENTS_COMMAND --raw-field owner=${OWNER_REPO_NAME%/*} --raw-field name=${OWNER_REPO_NAME#*/} --field number=$PR_NUMBER || true" \
		--bind "ctrl-u:execute-silent($GH_REMOVE_REACTION --raw-field id={1} --raw-field emoji=$REACTION_EMOJI)+reload:$GH_PR_COMMENTS_COMMAND --raw-field owner=${OWNER_REPO_NAME%/*} --raw-field name=${OWNER_REPO_NAME#*/} --field number=$PR_NUMBER || true" \
		--expect "ctrl-x,esc")

	case $(sed 1q <<<"${PR_COMMENT_OUTPUT}") in
	ctrl-x)
		gh issue comment "$PR_NUMBER" --repo "$OWNER_REPO_NAME"
		_load_indicator "Restarting ..." 0.25
		_fzf_pr_comment
		;;
	esc) _fzf_pr ;;
	esac
}

###################################### STARS

HELP_STAR_SECTION='cat <<<"
gh look star [-Flags] [Search term]

Flags  │ Description
───────│───────────────
<none> │ List your stars (sorted by the time the user set the star)
-U     │ List stars from a user
-w     │ Display the preview window upon start (default: hidden)

Head │ Description
─────│───────────────
⭐   │ Number of stargazers
🏁   │ Primary language

HotKeys  │ Description
─────────│───────────────
?        │ Toggle help
tab      │ Preview README
ctrl+b   │ Browser
ctrl+r   │ Preview release infos
ctrl+t   │ Star repo (useful for stars of another user)
ctrl+u   │ Unstar repo
ctrl+x   │ Write a comment
esc      │ Exit"'

_fzf_star() {
	FZF_DEFAULT_COMMAND=$'gh api graphql --paginate --raw-field query=\'query($endCursor: String, $USER_NAME:String! ) { user(login:$USER_NAME) { starredRepositories(orderBy: { field: STARRED_AT direction: DESC }, first: 100, after: $endCursor) { totalCount pageInfo { hasNextPage, endCursor } nodes { nameWithOwner primaryLanguage {name} stargazerCount viewerHasStarred pushedAt description }}}}\' --template \'
		{{- tablerow (printf "∑ %.0f Starred Repos" .data.user.starredRepositories.totalCount | color "yellow+h") ( "|" | color "white") ("? - Toggle Help" | color "blue+d") -}}{{- tablerender -}}
		{{- tablerow "" -}}{{- tablerender -}}
		{{- $headerColor := "yellow+b" -}}
			{{- tablerow ("REPO" | color $headerColor) "⭐" "🏁" ("LAST COMMIT" | color $headerColor) ("DESCRIPTION" | color $headerColor) -}}
		{{- range .data.user.starredRepositories.nodes -}}
		{{- $stargazerCount := printf "%.0f" .stargazerCount -}}
			{{- if gt .stargazerCount 1000000.0 -}}{{- $stargazerCount = ">1M" -}}
				{{- else if gt .stargazerCount 100000.0 -}}{{- $stargazerCount = printf "%.3sk" $stargazerCount -}}
				{{- else if gt .stargazerCount 10000.0 -}}{{- $stargazerCount = printf "%.2sk" $stargazerCount -}}
				{{- else if gt .stargazerCount 1000.0 -}}{{- $stargazerCount = printf "%.1sk" $stargazerCount -}}
				{{- else if eq .stargazerCount 0.0 -}}{{- $stargazerCount = "" -}}
			{{- end -}}
		{{- $stargazerColor := "yellow" -}}
			{{- if .viewerHasStarred }}{{ $stargazerColor = "black+b:yellow" }}{{ end -}}
		{{- $langName := "" -}}
			{{- if .primaryLanguage }}{{ $langName = .primaryLanguage.name }}{{ end -}}
			{{- if eq $langName "JavaScript" }}{{- $langName = "" -}}
				{{- else if eq $langName "Python" }}{{- $langName = "" -}}
			{{ end -}}
			{{- tablerow (.nameWithOwner | color "cyan+h") ($stargazerCount | color $stargazerColor) ($langName | color "green") (timeago .pushedAt | color "gray+h") .description -}}
		{{- end -}}\''" --raw-field USER_NAME=$USER_NAME" \
		GH_FORCE_TTY=100% fzf --ansi --no-multi --nth 1,3,7.. \
		--prompt $'\e[1;93mSearch  stars'" [$USER_NAME] > " --header "" --header-lines 3 \
		--preview "gh repo view {1}" --preview-window wrap:"$PREVIEW_WINDOW_VISIBILITY" \
		--query "$INITIAL_QUERY" --exact \
		--bind "?:toggle-preview+change-preview:$HELP_STAR_SECTION" \
		--bind 'tab:toggle-preview+change-preview(gh repo view {1})' \
		--bind "ctrl-b:execute-silent(gh repo view {1} --web)" \
		--bind $'ctrl-r:toggle-preview+change-preview([[ $(gh release list -R {1}) ]] && gh release view -R {1})' \
		--bind $'ctrl-t:execute-silent(gh api -X PUT /user/starred/{1})+reload(eval "$FZF_DEFAULT_COMMAND")' \
		--bind $'ctrl-u:execute-silent(gh api -X DELETE /user/starred/{1})+reload(eval "$FZF_DEFAULT_COMMAND")'
}

# TODO the statement [[...]] && ... || ... is a typical bash pitfall case, if the command after && fails the command after || gets executed as well (it should not); use a simple if ... else ... statement
# https://mywiki.wooledge.org/BashPitfalls#cmd1_.26.26_cmd2_.7C.7C_cmd3
# TODO listing the emoji the user used in the list, figure out how to get this information via graphql.
# TODO remove all my emojis from the issue when the hotkey is called.
# TODO it would be useful to store an emoji in the scratch file, but it must be visually clear which emoji is actively set when generating a reaction

REACTION_EMOJI="THUMBS_UP"
SORTING_ORDER=""
OWNER_REPO_NAME=""
USER_NAME=""
PREVIEW_WINDOW_VISIBILITY="hidden"
ISSUE_OUTPUT=""
ISSUE_COMMENT_OUTPUT=""
PR_OUTPUT=""
PR_COMMENT_OUTPUT=""
BAT_OR_CAT="cat"

if [ $# = 0 ]; then
	bash -c "$HELP_GENERAL"
	exit 1
else
	############# Check needed programs installed #############
	if ! command -v fzf >/dev/null; then
		echo Missing: fzf
		exit 1
	fi
	if command -v bat >/dev/null; then
		BAT_OR_CAT="bat --color always --language md --highlight-line :3 --style plain"
	fi

	############# Check needed scratch file exits and writeable #############
	# The purpose of this file is to signal to the fzf which search mode is active and remember the last one.
	# This allows switching between "Open" and "All issues/ prs" and active search within the selected category.
	SCRATCH_FILE="${BASH_SOURCE%/*}/.trashme"
	if [ ! -e "$SCRATCH_FILE" ]; then
		touch "$SCRATCH_FILE" 2>/dev/null || echo "Not allowed creating $SCRATCH_FILE"
	fi
	if [ ! -w "$SCRATCH_FILE" ]; then
		echo Not allowed writing to "$SCRATCH_FILE"
		exit 1
	fi
	GH_ADD_REACTION=$'gh api graphql --silent --raw-field query=\'mutation($id: ID! $emoji: ReactionContent! ) { addReaction(input: {subjectId: $id content: $emoji }) { clientMutationId }}\''
	GH_REMOVE_REACTION=$'gh api graphql --silent --raw-field query=\'mutation($id: ID! $emoji: ReactionContent! ) { removeReaction(input: {subjectId: $id content: $emoji }) { clientMutationId }}\''
	GH_COMMENTS_PREVIEW=$'printf "COMMENTER:\t%s\nDATE:\t\t%s\n%s" {3} {4..6} "$(gh api graphql --raw-field id={1} --raw-field query=\'query($id: ID!) {node(id: $id) {... on Comment {body} ... on Reactable { reactionGroups { content reactors { totalCount }}}}}\' --template \'{{ range .data.node.reactionGroups }}{{ $emoji := .content }}{{ if eq .content "CONFUSED" }}{{ $emoji = "😕" }}{{ else if eq .content "EYES" }}{{ $emoji = "👀" }}{{ else if eq .content "HEART" }}{{ $emoji = "❤️" }}{{ else if eq .content "HOORAY" }}{{ $emoji = "🎉" }}{{ else if eq .content "LAUGH" }}{{ $emoji = "😄" }}{{ else if eq .content "THUMBS_DOWN" }}{{ $emoji = "👎" }}{{ else if eq .content "THUMBS_UP" }}{{ $emoji = "👍" }}{{ else if eq .content "ROCKET" }}{{ $emoji = "🚀" }}{{ end }}{{ if gt .reactors.totalCount 0.0 }}{{ printf "%s %v  " $emoji .reactors.totalCount }}{{ end }}{{ end }}{{- tablerow "" -}}{{- tablerender -}}{{- tablerow "" -}}{{- tablerender -}}{{ .data.node.body}}\')" | '"$BAT_OR_CAT"
fi

while [ $# -gt 0 ]; do
	COMMAND_ARG="$1"
	case "$COMMAND_ARG" in
	issue | pr)
		shift
		while getopts :e:o:R:w flag; do
			case "$flag" in
			e)
				if [[ "CONFUSED EYES HEART HOORAY LAUGH THUMBS_DOWN THUMBS_UP ROCKET" =~ $OPTARG ]]; then
					REACTION_EMOJI="$OPTARG"
				else
					echo "!!! Search help, invalid emoji: $OPTARG"
					gh api zen
					exit 1
				fi
				;;
			o)
				if [[ "$OPTARG" =~ ^[A-Za-z-]{7,}$ ]]; then
					SORTING_ORDER="sort:$OPTARG"
				else
					echo "Search help, invalid sort order: $OPTARG !!!"
					gh api zen
					exit 1
				fi
				;;
			R)
				# local syntax test first to fail fast, and then gh api test
				# curl is faster, but has a small rate limit without authentication
				if [[ "$OPTARG" =~ ^[^:/]+/[^:/]+$ ]]; then
					OWNER_REPO_NAME="$OPTARG"
				else
					echo "!!! Respect the syntax: gh look {issue,pr} -R OWNER/REPO"
					gh api zen
					exit 1
				fi
				if ! gh api --silent repos/"$OWNER_REPO_NAME" 2>/dev/null; then
					echo "No GitHub repo called $OWNER_REPO_NAME !!!"
					gh api zen
					exit 1
				fi
				;;
			w) PREVIEW_WINDOW_VISIBILITY="nohidden" ;;
			*)
				grep -q "issue" <<<"$COMMAND_ARG" && bash -c "$HELP_ISSUE_SECTION"
				grep -q "pr" <<<"$COMMAND_ARG" && bash -c "$HELP_PR_SECTION"
				exit 0
				;;
			esac
		done
		# shift all processed options away, all that's left "$*" are non-options (aka mass-arguments/operands)
		shift "$((OPTIND - 1))"
		INITIAL_QUERY="$*"
		if [ -z "$OWNER_REPO_NAME" ]; then
			# if the OWNER_REPO_NAME is not set yet, check if the repo has a remote and assign the variable
			git ls-remote --get-url 2>/dev/null 1>&2 || exit 1
			OWNER_REPO_NAME="$(gh api graphql --field owner=:owner --field name=:repo --raw-field query=$'query ($owner: String!, $name: String!) { repository(owner: $owner, name: $name) { nameWithOwner }}' --jq '.[].repository.nameWithOwner')"
		fi
		grep -q "issue" <<<"$COMMAND_ARG" && _fzf_issue
		grep -q "pr" <<<"$COMMAND_ARG" && _fzf_pr
		;;
	star)
		shift
		while getopts :U:w flag; do
			case "$flag" in
			U)
				# local syntax test first to fail fast, and then gh api test
				if [[ "$OPTARG" =~ ^[^:/]+$ ]]; then
					USER_NAME="$OPTARG"
				else
					echo "!!! Respect the syntax: gh look star -U USER"
					exit 1
				fi
				if ! gh api --silent users/"$USER_NAME" 2>/dev/null; then
					echo "No USER called $USER_NAME !!!"
					gh api zen
					exit 1
				fi
				;;
			w) PREVIEW_WINDOW_VISIBILITY="nohidden" ;;
			*)
				bash -c "$HELP_STAR_SECTION"
				exit 1
				;;
			esac
		done
		shift "$((OPTIND - 1))"
		INITIAL_QUERY="$*"
		# if the USER_NAME is not set yet, use your own.
		if [ -z "$USER_NAME" ]; then
			USER_NAME="$(gh api graphql --raw-field query='{viewer{login}}' --jq '.data.viewer.login')"
		fi
		_fzf_star
		;;
	*)
		bash -c "$HELP_GENERAL"
		exit 1
		;;

	esac
done
