---
# https://github.com/reviewdog/action-shellcheck
name: Shellcheck workflow

on:
  push:
    branches:
      - main
  pull_request_target:
  workflow_dispatch:

jobs:
  shellcheck:
    name: Run shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: shellcheck® setup
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-check
          pattern: "gh-look"
          fail_on_error: true
          github_token: ${{ secrets.github_token }}
