---
name: Quality check

on:
  push:
    branches:
      - main
  pull_request_target:
  workflow_dispatch:

jobs:
  shellcheck:
    name: Run shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Vale Text Linter
        # https://github.com/errata-ai/vale-action
        uses: errata-ai/vale-action@reviewdog
        with:
          reporter: github-check
          fail_on_error: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: shellcheck® setup
        # https://github.com/reviewdog/action-shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-check
          pattern: "gh-look"
          fail_on_error: true
          github_token: ${{ secrets.github_token }}
